(* This file was autogenerated; don't edit it by hand *)

let tests () = OUnit.TestList [
    File_tail.ounit_tests ();
    File_writer.ounit_tests ();
    Import.ounit_tests ();
    Lock_file.ounit_tests ();
    Log.ounit_tests ();
    Persistent_singleton.ounit_tests ();
    Rpc.ounit_tests ();
    Rpc_intf.ounit_tests ();
    Std.ounit_tests ();
    Tcp.ounit_tests ();
    Tcp_file.ounit_tests ();
    Typed_tcp.ounit_tests ();
    Typed_tcp_intf.ounit_tests ();
    Unpack_sequence.ounit_tests ();
    Versioned_rpc.ounit_tests ();
    Versioned_typed_tcp.ounit_tests ();
    Weak_hashtbl.ounit_tests ();
];;

let run () =  ignore (OUnit.run_test_tt_main (tests ()):OUnit.test_result list)
